name: Build Plugin

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download project
        uses: actions/checkout@v4

      - name: Unzip project
        run: |
          unzip -o *.zip -d project

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Build plugin
        run: |
          cd project
          gradle build

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: AstralWeapons
          path: project/build/libs/*.jar
